name: masbaha_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  carousel_slider_plus: ^7.0.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DigitalNumbers
      fonts:
        - asset: assets/fonts/digital/DigitalNumbers-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-Black.ttf
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-Bold.ttf
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-ExtraBold.ttf
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-ExtraLight.ttf
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-Light.ttf
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-Medium.ttf
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-Regular.ttf
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-SemiBold.ttf
        - asset: assets/fonts/noto_kufi_ar/NotoKufiArabic-Thin.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
